package com.dyn.render.reference;

import java.util.Arrays;

import net.minecraftforge.fml.common.ModMetadata;

public class MetaData {
	public static ModMetadata init(ModMetadata metadata) {
		metadata.modId = Reference.MOD_ID;
		metadata.name = Reference.MOD_NAME;
		metadata.description = "This handles name overlays";
		metadata.url = "";
		metadata.version = Reference.VERSION;
		metadata.authorList = Arrays.asList("Dom Amato");
		metadata.credits = "";
		metadata.autogenerated = false;
		return metadata;
	}
}
